site_name: Jackbox Games
theme:
  name: material
site_url: https://craig-sd.github.io/JackboxGames/docs/
repo_url: https://github.com/craig-sd/JackboxGames/

nav:
    - Prepare: prepare.md
    - Play: play.md